### ISSUE TITLE
Tokenizer: NoSuchMethodError: com.johnsnowlabs.nlp.annotators.common.Sentence.start()

### ISSUE THREAD

**Issue by pobreiluso** [JohnSnowLabs/spark-nlp#113]
## Description

Tokenizer isn't working while using Python bindings for SparkNLP 1.4.
In SparkNLP 1.2.3 I used RegexTokenizer without any issue.

## Expected Behavior

I expected to get a list of tokens from product titles that I pased as parameters, for example.

["this is a product title"]  == should return ==> ["this", "is", "a","product","title"]

## Current Behavior

The scripts returns the error below.
`
py4j.protocol.Py4JJavaError: An error occurred while calling o67.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 7, www.host.com, executor 1): java.lang.NoSuchMethodError: com.johnsnowlabs.nlp.annotators.common.Sentence.start()I
`

## Steps to Reproduce

`import sys
from pyspark import HiveContext
from pyspark import SparkContext

from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *

spark = SparkContext(appName="ngrams_by_section")
hiveContext = HiveContext(spark)

getData = hiveContext.sql("""
    SELECT sentence, label
        FROM table
""");

data = getData
document_assembler = DocumentAssembler().setInputCol("sentence").setOutputCol("title")

tokenizer = Tokenizer().setInputCols(["title"]).setOutputCol("token").setTargetPattern("[A-Za-zÀ-úÀ-ÿ0-9ñÑ]+")

tokenizer_pipeline = Pipeline(stages=[
    document_assembler,
    tokenizer
    ]
    )

tokenizer_model = tokenizer_pipeline.fit(data)
ng = tokenizer_model.transform(data)
ng.show(truncate=False)`
## Context

I had some code working with Spark-nlp 1.2.3, recently I linked to 1.4.0 package and adpated my code to work with this version, but it isn't working anymore.

## Your Environment

* Version used: Spark 2.2.0 Scala 2.11
* Command executed:
spark-submit  --master yarn  --deploy-mode client  --driver-memory 2g  --executor-memory 2g  --num-executors 4  --executor-cores 4  --packages JohnSnowLabs:spark-nlp:1.4.0 nlp-bug-test.py

**Comment by saifjsl** [comment]
I am being unable to reproduce this issue, I have executed pyspark with 
`~/apps/spark-2.1.1-bin-hadoop2.7/bin/spark-submit --driver-memory 2g --executor-memory 2g --num-executors 4 --executor-cores 4 --packages JohnSnowLabs:spark-nlp:1.4.0 code.py`

with this following code
```
import sys
import os
from pyspark import HiveContext
from pyspark import SparkContext
from pyspark.sql import SparkSession

from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *

#spark = SparkContext(appName="ngrams_by_section")
spark = SparkSession.builder.getOrCreate()
hiveContext = HiveContext(spark)

#Load the input data to be annotated
data = spark. \
        read. \
        parquet("file:///" + os.getcwd() + "/../src/test/resources/sentiment.parquet"). \
        limit(1000)
data.cache()
data.count()
data.show()

document_assembler = DocumentAssembler().setInputCol("text").setOutputCol("title")

tokenizer = Tokenizer().setInputCols(["title"]).setOutputCol("token")

tokenizer_pipeline = Pipeline(stages=[
document_assembler,
tokenizer
]
)

tokenizer_model = tokenizer_pipeline.fit(data)
ng = tokenizer_model.transform(data)
ng.show(truncate=False)

```

**Comment by albertoandreottiATgmail** [comment]
I couldn't reproduce the problem either, looks to me like a classpath problem?

**Comment by pobreiluso** [comment]
Hi There and sorry for the late response, I have been messing around with this issue, and finally i can confirm that it was all related to a classpath issue.

If I run my spark-submit command within spark-nlp/python/ directory it works like a charm, otherwise it throws the reported error.
Now I am figuring some way to run my code while using virtualenv in cluster mode, but that's another history, and not matter of an Issue.

Thanks for your time, and sorry for the inconveniences.
