### ISSUE TITLE
Loading Pretrained Pipeline breaks with Databricks 10.2 ML, but works with 9.1 ML

### ISSUE THREAD

**Issue by chengyineng38** [JohnSnowLabs/spark-nlp#6805]
## Description
Loading Pretrained Pipeline breaks with Databricks Runtime 10.2ML, but works with 9.1 ML, while keeping the dependency versions the same:

spark-nlp==3.4.0
com.johnsnowlabs.nlp:spark-nlp_2.12:3.4.0

and including the below in Spark configurations
```
spark.kryoserializer.buffer.max 2000M
spark.serializer org.apache.spark.serializer.KryoSerializer
```

Code that breaks: 
```
from sparknlp.pretrained import PretrainedPipeline

rec_entities_pipeline = PretrainedPipeline("recognize_entities_dl", "en")
```

## Expected Behavior
It should return

```
Approx size to download 160.1 MB
[OK!]
```

## Current Behavior
Error: 
```
java.lang.NoClassDefFoundError: org/json4s/package$MappingException
```

Attaching the complete stack trace as a file here: 
[sparknlp_stacktrace.md](https://github.com/JohnSnowLabs/spark-nlp/files/7915999/sparknlp_stacktrace.md)

## Steps to Reproduce
[Here is a link](https://community.cloud.databricks.com/?o=3274638796062575#notebook/4048152495196613/command/4048152495196618) to the notebook where you can view the code. 

Also attaching a screenshot of the error and the code.
<img width="1078" alt="Screen Shot 2022-01-21 at 12 43 31 PM" src="https://user-images.githubusercontent.com/59850826/150583478-9af651e1-af61-416c-a3f3-6eb795c48efb.png">

## Context
This bug prevents Databricks users from upgrading to a higher runtime. 

## Your Environment
* spark-nlp==3.4.0
* com.johnsnowlabs.nlp:spark-nlp_2.12:3.4.0
* spark.kryoserializer.buffer.max 2000M
* spark.serializer org.apache.spark.serializer.KryoSerializer
* With fixing the above configurations constant, I am changing between DBR 10.2 ML and 9.1 LTS ML.

**Comment by maziyarpanahi** [comment]
Please pay attention to the NOTE at the end: https://github.com/JohnSnowLabs/spark-nlp#databricks-cluster

Runtime 9.x has a different spark/pyspark than Runtime 10.x, you need the right Maven package for each runtime.

**Comment by chengyineng38** [comment]
@maziyarpanahi Thanks, I missed out on the 3.1 vs 3.2 distinction! 

<img width="526" alt="Screen Shot 2022-01-21 at 3 02 25 PM" src="https://user-images.githubusercontent.com/59850826/150599709-624c6e08-3ee6-4336-89b2-8929f6d3479e.png">
