### ISSUE TITLE
USE pretrained download not working for sparknlp 3.4.4

### ISSUE THREAD

**Issue by drbonis** [JohnSnowLabs/spark-nlp#10938]
## Description

UniversalSentenceEncoder.pretrained("tfhub_use", "en") is not working for sparknlp version 3.4.4 (but it works with the sparknlp 4.0.2 version of sparknlp).

```
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: org/json4s/package$MappingException
```

## Expected Behavior

Should download the USE model for version 3.4.4

## Possible Solution

```
Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: org/json4s/package$MappingException
```

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Spark NLP version `sparknlp.version()`: 3.4.4
* Apache NLP version `spark.version`: 3.2.0
* Java version `java -version`:
* Setup and installation (Pypi, Conda, Maven, etc.): Google colab bash script
* Operating System and version: Google colab
* Link to your project (if any):

**Comment by maziyarpanahi** [comment]
```
org/json4s/package$MappingException
```
wrong pyspark version.


- spark-nlp 3.4.x requires `spark-nlp-spark32` or `sparknlp.start(spark32=True)` for pyspark 3.2
- spark-nlp 4.x works with all PySpark versions
