### ISSUE TITLE
TypeError: setDictionary() got an unexpected keyword argument 'key_delimiter'

### ISSUE THREAD

**Issue by shashishekhard** [JohnSnowLabs/spark-nlp#132]
Tried running the dictionary-sentiment example in python, it gives a type error for set dictionary call in Lemmatizer. 
.setDictionary("../../../src/main/resources/lemma-corpus/AntBNC_lemmas_ver_001.txt", key_delimiter="->", value_delimiter="\t")
## Description

Took the dictionary sentiment example in pyspark and ran on Hortonworks sandbox. It returns a Type Error saying key_delimiter is an unexpected keyword.
Traceback (most recent call last):
  File "/home/maria_dev/pyspark/spark-nlp.py", line 39, in <module>
    .setDictionary("../../../src/main/resources/lemma-corpus/AntBNC_lemmas_ver_001.txt", key_delimiter="->", value_delimiter="\t")
TypeError: setDictionary() got an unexpected keyword argument 'key_delimiter'
## Possible Solution

The following changes were made and it worked fine. 
.setDictionary("../../../src/main/resources/lemma-corpus/AntBNC_lemmas_ver_001.txt", options={"format":"text", "keyDelimiter":"->", "valueDelimiter":"\t"})
## Your Environment

* Version used: 1.4.0
* Browser Name and version:
* Operating System and version (desktop or mobile): Hortonworks Sandbox 2.6.3 with CentOS
* Link to your project:NA

**Comment by saifjsl** [comment]
thank  you @shashishekhard ! will take a look asap. Can you please confirm whether this happens on 1.4.1 as well?

**Comment by shashishekhard** [comment]
Hi @saifjsl it works perfectly with 1.4.1. No issues. Thank you.
