### ISSUE TITLE
java.lang.NoClassDefFoundError: org/json4s/package$MappingException

### ISSUE THREAD

**Issue by zim32** [JohnSnowLabs/spark-nlp#13124]
## Description
Trying to download pretrained model causes **java.lang.NoClassDefFoundError: org/json4s/package$MappingException**

```
lemmatizer = LemmatizerModel.pretrained("lemma_gsd", "ru").setInputCols(["sentences", "token"]).setOutputCol("lemma")
```

## Expected Behavior
No exception while downloading model

## Current Behavior
Exception is thrown

## Your Environment
* Spark NLP version `3.4.3`:
* Apache NLP version `3.3.1`:
* Java version `openjdk 17.0.5 2022-10-18 LTS`:
* python version `3.9.2`
* Setup and installation (pip): pip install spark-nlp==3.4.3
* Operating System and version: debian bullseye

I am running pyspark using 

`pyspark --packages com.johnsnowlabs.nlp:spark-nlp_2.12:3.4.3`

Full stack trace:

```
>>> lemmatizer = LemmatizerModel.pretrained("lemma_gsd", "ru").setInputCols(["sentences", "token"]).setOutputCol("lemma")
lemma_gsd download started this may take some time.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/sparknlp/annotator.py", line 2046, in pretrained
    return ResourceDownloader.downloadModel(LemmatizerModel, name, lang, remote_loc)
  File "/usr/local/lib/python3.9/dist-packages/sparknlp/pretrained.py", line 50, in downloadModel
    file_size = _internal._GetResourceSize(name, language, remote_loc).apply()
  File "/usr/local/lib/python3.9/dist-packages/sparknlp/internal.py", line 234, in __init__
    super(_GetResourceSize, self).__init__(
  File "/usr/local/lib/python3.9/dist-packages/sparknlp/internal.py", line 165, in __init__
    self._java_obj = self.new_java_obj(java_obj, *args)
  File "/usr/local/lib/python3.9/dist-packages/sparknlp/internal.py", line 175, in new_java_obj
    return self._new_java_obj(java_class, *args)
  File "/home/zim32/spark-3.3.1-bin-hadoop3/python/pyspark/ml/wrapper.py", line 86, in _new_java_obj
    return java_obj(*java_args)
  File "/home/zim32/spark-3.3.1-bin-hadoop3/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/home/zim32/spark-3.3.1-bin-hadoop3/python/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/zim32/spark-3.3.1-bin-hadoop3/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize.
: java.lang.NoClassDefFoundError: org/json4s/package$MappingException
        at org.json4s.ext.EnumNameSerializer.deserialize(EnumSerializer.scala:53)
        at org.json4s.Formats$$anonfun$customDeserializer$1.applyOrElse(Formats.scala:66)
        at org.json4s.Formats$$anonfun$customDeserializer$1.applyOrElse(Formats.scala:66)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:180)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:167)
        at scala.collection.AbstractTraversable.collectFirst(Traversable.scala:108)
        at org.json4s.Formats$.customDeserializer(Formats.scala:66)
        at org.json4s.Extraction$.customOrElse(Extraction.scala:775)
        at org.json4s.Extraction$.extract(Extraction.scala:454)
        at org.json4s.Extraction$.extract(Extraction.scala:56)
        at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:22)
        at com.johnsnowlabs.util.JsonParser$.parseObject(JsonParser.scala:28)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.parseJson(ResourceMetadata.scala:106)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.applyOrElse(ResourceMetadata.scala:138)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$$anonfun$readResources$1.applyOrElse(ResourceMetadata.scala:136)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at scala.collection.Iterator$$anon$13.next(Iterator.scala:593)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
        at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
        at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
        at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
        at scala.collection.AbstractIterator.to(Iterator.scala:1431)
        at scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
        at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
        at scala.collection.AbstractIterator.toList(Iterator.scala:1431)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:136)
        at com.johnsnowlabs.nlp.pretrained.ResourceMetadata$.readResources(ResourceMetadata.scala:130)
        at com.johnsnowlabs.client.aws.AWSGateway.getMetadata(AWSGateway.scala:94)
        at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.downloadMetadataIfNeed(S3ResourceDownloader.scala:65)
        at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.resolveLink(S3ResourceDownloader.scala:70)
        at com.johnsnowlabs.nlp.pretrained.S3ResourceDownloader.getDownloadSize(S3ResourceDownloader.scala:204)
        at com.johnsnowlabs.nlp.pretrained.ResourceDownloader$.getDownloadSize(ResourceDownloader.scala:546)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader$.getDownloadSize(ResourceDownloader.scala:712)
        at com.johnsnowlabs.nlp.pretrained.PythonResourceDownloader.getDownloadSize(ResourceDownloader.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
        at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.json4s.package$MappingException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 51 more

```

**Comment by maziyarpanahi** [comment]
Hi @zim32 

You are using a very recent version of `Apache Spark 3.3.x`, could you please also use a recent version of `Spark NLP 4.2.3`? `com.johnsnowlabs.nlp:spark-nlp_2.12:4.2.3` (https://github.com/JohnSnowLabs/spark-nlp#packages-cheatsheet)

Here is an example on Colab, keep in mind the inputCols for LemmatizerModel accepts 1 input only) 
- notebook: https://colab.research.google.com/drive/1q_PS_IeDTVIEVabnbquk3cLXpoJgFwXy?usp=sharing
- APIs: https://nlp.johnsnowlabs.com/api/python/reference/autosummary/python/sparknlp/annotator/lemmatizer/index.html#python.sparknlp.annotator.lemmatizer.LemmatizerModel

**Comment by zim32** [comment]
I can not use recent version of Spark NLP because model I want to download requires spark nlp 3.4.3

**Comment by zim32** [comment]
I will try to download order version of Apache Spark, for example 3.1.3, which should be compatible with Spark NLP 3.4.3

**Comment by zim32** [comment]
> Here is an example on Colab, keep in mind the inputCols for LemmatizerModel accepts 1 input only)

So why in this model page they provide two parameters to lemmatizer model?

https://nlp.johnsnowlabs.com/2022/03/31/lemma_taiga_ru_3_0.html

**Comment by maziyarpanahi** [comment]
> I can not use recent version of Spark NLP because model I want to download requires spark nlp 3.4.3
There is no model that is not available (nor works) for a recent version of Spark NLP. Please try it first and it will work. The reason it says 3.4.3 is that it just works for that and above. Even if there is a model that fails for recent version of Spark NLP you can just report them and we will provide the working version

> I will try to download order version of Apache Spark, for example 3.1.3, which should be compatible with Spark NLP 3.4.3
Please do not go back to previous releases, if you face any bugs they are either fixed or won't be fixed for those that were released a long time ago. It's safe to stay with recent versions

> So why in this model page they provide two parameters to lemmatizer model?
It's simple, it's wrong! You report and we fix it 👍🏼 


If you follow my notebook on Colab, you can use the same to report any model that is not working with the Spark NLP 4.2.x and we shall fix it

**Comment by zim32** [comment]
Ok I give up ) With spark 3.1.3  and spark nlp 3.4.3 I now get 

Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/spi/Filter

**Comment by zim32** [comment]
Ok thanks for your answers, I will try recent versions, I just thought that maybe older versions of spark nlp have two parameters in lemmatizer and thats why I need older versions

**Comment by maziyarpanahi** [comment]
> Ok I give up ) With spark 3.1.3 and spark nlp 3.4.3 I now get
> 
> Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/spi/Filter

My answer above, please follow the notebook and stay on the most recent versons of Apache Spark and Spark NLP. (you can also provide a simple notebook here and I can check)

**Comment by maziyarpanahi** [comment]
> Ok thanks for your answers, I will try recent versions, I just thought that maybe older versions of spark nlp have two parameters in lemmatizer and thats why I need older versions

You are very welcome. It's our fault, the example was wrong and I will make an issue right now to fix this immediately. (but everything that was working for previous versions `must` work for Spark NLP 4.2.x as well, otherwise, we make it work 👍🏼 )
